driver: ldap
ldap:
  url: ldaps://ldap.example.com
  bind_user: cn=root,dc=example,dc=com
  # Either bind_pass or bind_pass_file must be specified, but not both
  bind_pass: password
  # bind_pass_file: /path/to/password/file
  basedn: ou=Users,dc=example,dc=com
  filter: (memberOf=cn=public,ou=Groups,dc=example,dc=com)
  user_attr: uid
  attributes:
    - uid
    - mail
    - cn
  template: configs/ldap.gotempl
